services:
  mysql:
    image: 'mysql:8.0' # Es mejor usar una versión específica (8.0) que 'latest' para evitar que se rompa en el futuro
    environment:
      - 'MYSQL_DATABASE=flytrack_db'
      - 'MYSQL_ROOT_PASSWORD=admin123' # Alineado con tu properties
      - 'MYSQL_USER=flytrack'          # Usuario extra opcional
      - 'MYSQL_PASSWORD=flytrack123'   # Contraseña del usuario extra
    ports:
      - '3306:3306' # Lo cambié de 3307 a 3306 para que encaje con tu properties
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # Comando específico de MySQL
      timeout: 20s
      retries: 10