sonar.projectKey=angie_FlyTrack
sonar.organization=angie-91d
sonar.projectName=FlyTrack
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.java.libraries=build/libs/*.jar
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
