# Test Profile - GitHub Actions
spring.application.name=devops

# MySQL - Test Environment (Soporta variables de entorno de CI/CD)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/flytrack_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Puerto
server.port=8080

# Security (Quemado solo para pruebas)
spring.security.user.name=admin
spring.security.user.password=admin123

# Logging (Silenciado para no ensuciar la consola de GitHub Actions)
logging.level.root=WARN
logging.level.co.uniquindio.software=INFO