spring.application.name=devops

# MariaDB - En producción, usaría variables de entorno o secretos
spring.datasource.url=jdbc:mariadb://${DB_HOST:mariadb-prod}:${DB_PORT:3306}/${DB_NAME:flytrack_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Puerto
server.port=8080

# Security
spring.security.user.name=${SECURITY_USER}
spring.security.user.password=${SECURITY_PASSWORD}

# Actuator para health checks
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized

# Logging en producción
logging.level.root=INFO
logging.level.co.uniquindio.software=INFO

