# Test Profile - GitHub Actions
spring.application.name=devops

# MariaDB - Test Environment
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/flytrack_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Puerto
server.port=8080

# Security
spring.security.user.name=admin
spring.security.user.password=admin123

# Logging
logging.level.root=WARN
logging.level.co.uniquindio.software.devops=INFO

