spring.application.name=devops

# MySQL - Entorno de Staging
# OJO: Tu docker-compose.staging.yml debe tener un servicio llamado "mysql-staging"
spring.datasource.url=jdbc:mysql://mysql-staging:3306/flytrack_db
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
# En staging usamos "update" para probar cómo reacciona la BD a los cambios sin borrar los datos de prueba
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Puerto
server.port=8080

# Security
spring.security.user.name=admin
spring.security.user.password=admin123

# Actuator para health checks (Vital para Docker/Kubernetes)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized